### ISSUE TITLE
请问怎么刮削gyutto上的内容？

### ISSUE THREAD

**Issue by miechidandao** [CheerChen/better-av-tool#13]
我按照wiki执行了步骤，但似乎程序只能从dmm上爬取内容，在dmm上没搜索到信息就直接开始刮削下一步影片了

**Comment by CheerChen** [comment]
gyutto 的页面解析是没问题的；但是查询页出了问题，所以现在通过文件名(一般是日文)没法定位到对应的影片详细页
新版本暂时先去掉了，以后再研究怎么对应，打算不用 gyutto 直接查询 getchu

**Comment by CheerChen** [comment]
哦，我没看懂你的问题，你说的是怎么触发gyutto的抓取是吧，文件名需要有关键字“Sex Syndrome”或者“Sex Friend”

> 我按照wiki执行了步骤，但似乎程序只能从dmm上爬取内容，在dmm上没搜索到信息就直接开始刮削下一步影片了
