### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by RuyiXP** [CheerChen/better-av-tool#2]
win10 1909下运行之后报切片错误，去掉proxy参数也是一样，不知是什么原因？谢谢！

PS C:\Users\XXX\Downloads> .\better-av-tool-v0.8.1-win64.exe -output "I:\Ero\bat" -path "I:\Ero\FC2" -proxy "socks5://127.0.0.1:10808"
2020-02-21 09:56:51.300 INFO    better-av-tool/main.go:123      num PPV-1042868 match!
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main.func2(0xc00005a4c0, 0x1e, 0x83a580, 0xc0001084d0, 0x0, 0x0, 0x1e, 0x2)
        E:/Work/better-av-tool/main.go:135 +0x14c4
path/filepath.walk(0xc00005a4c0, 0x1e, 0x83a580, 0xc0001084d0, 0x7d3220, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:358 +0x42d
path/filepath.walk(0xc00005c0d0, 0xa, 0x83a580, 0xc000108070, 0x7d3220, 0x0, 0x832a60)
        c:/go/src/path/filepath/path.go:382 +0x307
path/filepath.Walk(0xc00005c0d0, 0xa, 0x7d3220, 0x0, 0xc0000a2140)
        c:/go/src/path/filepath/path.go:404 +0x106
main.main()
        E:/Work/better-av-tool/main.go:171 +0x10f

**Comment by tang2554** [comment]
同样出现了切片错误，win10 LTSC
D:\Downloads\Video>better-av-tool.exe -output "D:\Downloads\Video\output" -path "D:\Downloads\Video\jav" -proxy "socks5://127.0.0.1:8883"
2020-02-26 14:19:16.633 INFO    better-av-tool/main.go:123      num PPV-769077 match!
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.main.func2(0xc00008e150, 0x29, 0x83a580, 0xc000108150, 0x0, 0x0, 0x29, 0x2)
        E:/Work/better-av-tool/main.go:135 +0x14c4
path/filepath.walk(0xc00008e150, 0x29, 0x83a580, 0xc000108150, 0x7d3220, 0x0, 0x0)
        c:/go/src/path/filepath/path.go:358 +0x42d
path/filepath.walk(0xc00005a1c0, 0x16, 0x83a580, 0xc000108070, 0x7d3220, 0x0, 0x832a60)
        c:/go/src/path/filepath/path.go:382 +0x307
path/filepath.Walk(0xc00005a1c0, 0x16, 0x7d3220, 0x0, 0xc0000a2140)
        c:/go/src/path/filepath/path.go:404 +0x106
main.main()
        E:/Work/better-av-tool/main.go:171 +0x10f

**Comment by CheerChen** [comment]
你好，是获取年份的错误， #3 版本v0.9.0已修复
