### ISSUE TITLE
d_cos0113.mp4刮削失败

### ISSUE THREAD

**Issue by miechidandao** [CheerChen/better-av-tool#22]
在dmm上可以搜到这个影片，但是程序显示
[INFO] 2021/11/15 23:52 detect content utf-8 false
[ERRO] 2021/11/15 23:52 record not found
[INFO] 2021/11/15 23:51 fetching https://www.dmm.co.jp/digital/-/list/search/=/?searchstr=cos0113
之后闪退了

**Comment by CheerChen** [comment]
Sorry，目前只能刮削  [动画](https://www.dmm.co.jp/digital/) 以及 [通贩](https://www.dmm.co.jp/mono/) 分类下面的番号，d_cos0113属于同人分类下的作品
